###############################################################
#  Generated by:      Cadence Innovus 23.37-s090_1
#  OS:                Linux x86_64(Host ID iclab)
#  Generated on:      Sun May 17 20:54:26 2026
#  Design:            viterbi_decoder
#  Command:           write_db postRouteOpt
###############################################################
current_design viterbi_decoder
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
set_units -time 1ns -capacitance 1pf
create_clock [get_ports {clk}]  -name clk -period 5.000000 -waveform {0.000000 2.500000}
#END OF CLOCK SECTION#
set_load -pin_load -max  0.1  [get_ports {o_data[7]}]
set_load -pin_load -min  0.1  [get_ports {o_data[7]}]
set_load -pin_load -max  0.1  [get_ports {o_data[6]}]
set_load -pin_load -min  0.1  [get_ports {o_data[6]}]
set_load -pin_load -max  0.1  [get_ports {o_data[5]}]
set_load -pin_load -min  0.1  [get_ports {o_data[5]}]
set_load -pin_load -max  0.1  [get_ports {o_data[4]}]
set_load -pin_load -min  0.1  [get_ports {o_data[4]}]
set_load -pin_load -max  0.1  [get_ports {o_data[3]}]
set_load -pin_load -min  0.1  [get_ports {o_data[3]}]
set_load -pin_load -max  0.1  [get_ports {o_data[2]}]
set_load -pin_load -min  0.1  [get_ports {o_data[2]}]
set_load -pin_load -max  0.1  [get_ports {o_data[1]}]
set_load -pin_load -min  0.1  [get_ports {o_data[1]}]
set_load -pin_load -max  0.1  [get_ports {o_data[0]}]
set_load -pin_load -min  0.1  [get_ports {o_data[0]}]
set_load -pin_load -max  0.1  [get_ports {o_done}]
set_load -pin_load -min  0.1  [get_ports {o_done}]
set_wire_load_mode enclosed
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[14]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[6]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {rst_n}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[12]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[4]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[10]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[2]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[0]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[9]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[15]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[7]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[13]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[5]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[11]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[3]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[1]}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {en}]
set_input_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {i_data[8]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[7]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[5]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[3]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[1]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_done}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[6]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[4]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[2]}]
set_output_delay -add_delay 1 -clock [get_clocks {clk}] [get_ports {o_data[0]}]
set_clock_uncertainty 0.15 [get_clocks {clk}]
