
// Generated by Cadence Genus(TM) Synthesis Solution 23.17-s085_1
// Generated on: May 17 2026 19:54:15 +07 (May 17 2026 12:54:15 UTC)

// Verification Directory fv/viterbi_decoder 

module viterbi_decoder(clk, rst_n, en, i_data, o_data, o_done);
  input clk, rst_n, en;
  input [15:0] i_data;
  output [7:0] o_data;
  output o_done;
  wire clk, rst_n, en;
  wire [15:0] i_data;
  wire [7:0] o_data;
  wire o_done;
  wire [1:0] pm00;
  wire [1:0] pm10;
  wire [1:0] pm11;
  wire [1:0] pm01;
  wire [3:0] dec_s5;
  wire [3:0] dec_s3;
  wire [3:0] dec_s2;
  wire [3:0] dec_s4;
  wire [1:0] dec_s6;
  wire [15:0] rx_reg;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, dec_s7, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_261, \u_memory_rx_reg[0]_297 , \u_memory_rx_reg[1]_298
       , \u_memory_rx_reg[2]_299 , \u_memory_rx_reg[3]_300 ,
       \u_memory_rx_reg[4]_301 , \u_memory_rx_reg[5]_302 ;
  wire \u_memory_rx_reg[6]_303 , \u_memory_rx_reg[7]_304 ,
       \u_memory_rx_reg[8]_305 , \u_memory_rx_reg[9]_306 ,
       \u_memory_rx_reg[10]_307 , \u_memory_rx_reg[11]_308 ;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  DFFRX1 \u_memory_pm00_reg[0] (.RN (rst_n), .CK (clk), .D (n_237), .Q
       (pm00[0]), .QN (n_24));
  DFFSX1 \u_memory_pm10_reg[1] (.SN (rst_n), .CK (clk), .D (n_240), .Q
       (pm10[1]), .QN (n_23));
  DFFRX1 \u_memory_pm00_reg[1] (.RN (rst_n), .CK (clk), .D (n_239), .Q
       (pm00[1]), .QN (n_18));
  DFFSX1 \u_memory_pm10_reg[0] (.SN (rst_n), .CK (clk), .D (n_232), .Q
       (pm10[0]), .QN (UNCONNECTED));
  DFFSX1 \u_memory_pm11_reg[1] (.SN (rst_n), .CK (clk), .D (n_235), .Q
       (pm11[1]), .QN (n_51));
  DFFSX1 \u_memory_pm01_reg[1] (.SN (rst_n), .CK (clk), .D (n_231), .Q
       (pm01[1]), .QN (n_34));
  DFFSX1 \u_memory_pm01_reg[0] (.SN (rst_n), .CK (clk), .D (n_230), .Q
       (pm01[0]), .QN (UNCONNECTED0));
  DFFSX1 \u_memory_pm11_reg[0] (.SN (rst_n), .CK (clk), .D (n_229), .Q
       (pm11[0]), .QN (n_1));
  OAI221X1 g6481__2398(.A0 (n_238), .A1 (n_222), .B0 (n_23), .B1
       (n_234), .C0 (n_233), .Y (n_240));
  OAI22X1 g6483__5107(.A0 (n_238), .A1 (n_228), .B0 (n_18), .B1
       (n_236), .Y (n_239));
  OAI22X1 g6478__6260(.A0 (n_238), .A1 (n_227), .B0 (n_24), .B1
       (n_236), .Y (n_237));
  OAI221X1 g6480__4319(.A0 (n_238), .A1 (n_213), .B0 (n_51), .B1
       (n_234), .C0 (n_233), .Y (n_235));
  OAI211X1 g6476__8428(.A0 (n_238), .A1 (n_223), .B0 (n_233), .C0
       (n_54), .Y (n_232));
  OAI221X1 g6482__5526(.A0 (n_238), .A1 (n_207), .B0 (n_34), .B1
       (n_234), .C0 (n_233), .Y (n_231));
  DFFRX1 \u_memory_dec_s5_reg[0] (.RN (rst_n), .CK (clk), .D (n_224),
       .Q (dec_s5[0]), .QN (UNCONNECTED1));
  DFFRX1 \u_memory_dec_s3_reg[0] (.RN (rst_n), .CK (clk), .D (n_218),
       .Q (dec_s3[0]), .QN (UNCONNECTED2));
  DFFRX1 \u_memory_dec_s5_reg[2] (.RN (rst_n), .CK (clk), .D (n_216),
       .Q (dec_s5[2]), .QN (UNCONNECTED3));
  OAI211X1 g6477__6783(.A0 (n_238), .A1 (n_203), .B0 (n_233), .C0
       (n_53), .Y (n_230));
  OAI211X1 g6479__3680(.A0 (n_238), .A1 (n_209), .B0 (n_233), .C0
       (n_55), .Y (n_229));
  DFFRX1 \u_memory_dec_s3_reg[2] (.RN (rst_n), .CK (clk), .D (n_219),
       .Q (dec_s3[2]), .QN (UNCONNECTED4));
  DFFRX1 u_memory_dec_s7_reg(.RN (rst_n), .CK (clk), .D (n_214), .Q
       (dec_s7), .QN (n_0));
  AOI22X1 g6494__1617(.A0 (n_196), .A1 (n_226), .B0 (n_201), .B1
       (n_225), .Y (n_228));
  AOI22X1 g6495__2802(.A0 (n_197), .A1 (n_226), .B0 (n_184), .B1
       (n_225), .Y (n_227));
  DFFRX1 \u_memory_dec_s5_reg[1] (.RN (rst_n), .CK (clk), .D (n_210),
       .Q (dec_s5[1]), .QN (UNCONNECTED5));
  DFFRX1 \u_memory_dec_s3_reg[1] (.RN (rst_n), .CK (clk), .D (n_204),
       .Q (dec_s3[1]), .QN (UNCONNECTED6));
  DFFRX1 \u_memory_dec_s5_reg[3] (.RN (rst_n), .CK (clk), .D (n_212),
       .Q (dec_s5[3]), .QN (UNCONNECTED7));
  DFFRX1 \u_memory_dec_s3_reg[3] (.RN (rst_n), .CK (clk), .D (n_205),
       .Q (dec_s3[3]), .QN (UNCONNECTED8));
  MX2X1 g6493__1705(.A (n_226), .B (dec_s5[0]), .S0 (n_215), .Y
       (n_224));
  AOI22X1 g6496__5122(.A0 (n_193), .A1 (n_221), .B0 (n_183), .B1
       (n_220), .Y (n_223));
  AOI22X1 g6497__8246(.A0 (n_192), .A1 (n_221), .B0 (n_200), .B1
       (n_220), .Y (n_222));
  MX2X1 g6505__7098(.A (dec_s3[2]), .B (n_221), .S0 (n_217), .Y
       (n_219));
  MX2X1 g6503__6131(.A (dec_s3[0]), .B (n_226), .S0 (n_217), .Y
       (n_218));
  MX2X1 g6500__1881(.A (n_221), .B (dec_s5[2]), .S0 (n_215), .Y
       (n_216));
  MX2X1 g6507__5115(.A (dec_s7), .B (n_226), .S0 (n_145), .Y (n_214));
  AOI22X1 g6501__7482(.A0 (n_186), .A1 (n_211), .B0 (n_195), .B1
       (n_208), .Y (n_213));
  MX2X1 g6499__4733(.A (n_211), .B (dec_s5[3]), .S0 (n_215), .Y
       (n_212));
  MX2X1 g6498__6161(.A (n_206), .B (dec_s5[1]), .S0 (n_215), .Y
       (n_210));
  AOI22X1 g6502__9315(.A0 (n_187), .A1 (n_211), .B0 (n_181), .B1
       (n_208), .Y (n_209));
  AOI22X1 g6508__9945(.A0 (n_189), .A1 (n_206), .B0 (n_199), .B1
       (n_202), .Y (n_207));
  MX2X1 g6506__2883(.A (dec_s3[3]), .B (n_211), .S0 (n_217), .Y
       (n_205));
  MX2X1 g6504__2346(.A (dec_s3[1]), .B (n_206), .S0 (n_217), .Y
       (n_204));
  AOI22X1 g6509__1666(.A0 (n_190), .A1 (n_206), .B0 (n_179), .B1
       (n_202), .Y (n_203));
  INVX2 g6511(.A (n_226), .Y (n_225));
  CLKINVX2 g6510(.A (n_220), .Y (n_221));
  CLKAND2X2 g6513__7410(.A (n_201), .B (n_198), .Y (n_226));
  INVX2 g6514(.A (n_202), .Y (n_206));
  NAND2X1 g6512__6417(.A (n_200), .B (n_194), .Y (n_220));
  INVX2 g6515(.A (n_208), .Y (n_211));
  NAND2X1 g6516__5477(.A (n_199), .B (n_191), .Y (n_202));
  OAI21X1 g6518__2398(.A0 (n_197), .A1 (n_185), .B0 (n_196), .Y
       (n_198));
  NAND2X1 g6517__5107(.A (n_195), .B (n_188), .Y (n_208));
  OAI21X1 g6519__6260(.A0 (n_193), .A1 (n_182), .B0 (n_192), .Y
       (n_194));
  OAI21X1 g6520__4319(.A0 (n_190), .A1 (n_178), .B0 (n_189), .Y
       (n_191));
  OAI21X1 g6521__8428(.A0 (n_187), .A1 (n_180), .B0 (n_186), .Y
       (n_188));
  CLKINVX1 g6531(.A (n_184), .Y (n_185));
  CLKINVX1 g6533(.A (n_182), .Y (n_183));
  CLKINVX1 g6530(.A (n_180), .Y (n_181));
  OR2X1 g6525__5526(.A (n_177), .B (n_169), .Y (n_200));
  CLKINVX1 g6532(.A (n_178), .Y (n_179));
  AOI211X1 g6539__6783(.A0 (n_176), .A1 (n_158), .B0 (n_156), .C0
       (n_155), .Y (n_182));
  OAI211X1 g6535__3680(.A0 (n_177), .A1 (n_147), .B0 (n_154), .C0
       (n_157), .Y (n_184));
  NAND2X1 g6522__1617(.A (n_176), .B (n_160), .Y (n_192));
  NAND2X1 g6523__2802(.A (n_176), .B (n_168), .Y (n_201));
  NAND2X1 g6527__1705(.A (n_174), .B (n_175), .Y (n_199));
  NAND2X1 g6529__5122(.A (n_173), .B (n_175), .Y (n_195));
  AOI211X1 g6534__8246(.A0 (n_174), .A1 (n_172), .B0 (n_171), .C0
       (n_170), .Y (n_180));
  AOI211X1 g6537__7098(.A0 (n_173), .A1 (n_172), .B0 (n_171), .C0
       (n_170), .Y (n_178));
  OAI211X1 g6536__6131(.A0 (n_177), .A1 (n_164), .B0 (n_163), .C0
       (n_162), .Y (n_193));
  NAND2X1 g6528__1881(.A (n_173), .B (n_161), .Y (n_189));
  OR2X1 g6524__5115(.A (n_177), .B (n_159), .Y (n_196));
  OAI211X1 g6538__7482(.A0 (n_13), .A1 (n_167), .B0 (n_166), .C0
       (n_165), .Y (n_187));
  CLKINVX1 g6543(.A (n_168), .Y (n_169));
  OAI211X1 g6541__4733(.A0 (n_10), .A1 (n_167), .B0 (n_166), .C0
       (n_165), .Y (n_190));
  OAI211X1 g6540__6161(.A0 (n_4), .A1 (n_164), .B0 (n_163), .C0
       (n_162), .Y (n_197));
  NAND2X1 g6542__9315(.A (n_174), .B (n_161), .Y (n_186));
  CLKINVX1 g6544(.A (n_159), .Y (n_160));
  AOI21X1 g6545__9945(.A0 (n_151), .A1 (n_152), .B0 (n_158), .Y
       (n_168));
  CLKINVX1 g6559(.A (n_156), .Y (n_157));
  CLKINVX1 g6560(.A (n_154), .Y (n_155));
  AOI21X1 g6549__2883(.A0 (n_153), .A1 (n_150), .B0 (n_172), .Y
       (n_175));
  DFFRX1 \u_memory_dec_s2_reg[0] (.RN (rst_n), .CK (clk), .D (n_137),
       .Q (dec_s2[0]), .QN (UNCONNECTED9));
  DFFRX1 \u_memory_dec_s2_reg[2] (.RN (rst_n), .CK (clk), .D (n_139),
       .Q (dec_s2[2]), .QN (UNCONNECTED10));
  DFFRX1 \u_memory_dec_s4_reg[2] (.RN (rst_n), .CK (clk), .D (n_138),
       .Q (dec_s4[2]), .QN (UNCONNECTED11));
  DFFRX1 \u_memory_dec_s4_reg[0] (.RN (rst_n), .CK (clk), .D (n_140),
       .Q (dec_s4[0]), .QN (UNCONNECTED12));
  DFFRX1 \u_memory_dec_s6_reg[0] (.RN (rst_n), .CK (clk), .D (n_146),
       .Q (dec_s6[0]), .QN (UNCONNECTED13));
  OAI21X1 g6546__2346(.A0 (n_153), .A1 (n_148), .B0 (n_164), .Y
       (n_159));
  AOI21X1 g6548__1666(.A0 (n_153), .A1 (n_149), .B0 (n_144), .Y
       (n_161));
  NOR2X1 g6563__7410(.A (n_153), .B (n_152), .Y (n_156));
  NAND2X1 g6564__6417(.A (n_153), .B (n_152), .Y (n_154));
  NOR2X1 g6567__5477(.A (n_151), .B (n_150), .Y (n_171));
  AND2X1 g6568__2398(.A (n_150), .B (n_151), .Y (n_170));
  DFFRX1 \u_memory_dec_s2_reg[1] (.RN (rst_n), .CK (clk), .D (n_133),
       .Q (dec_s2[1]), .QN (UNCONNECTED14));
  DFFRX1 \u_memory_dec_s4_reg[1] (.RN (rst_n), .CK (clk), .D (n_132),
       .Q (dec_s4[1]), .QN (UNCONNECTED15));
  DFFRX1 \u_memory_dec_s6_reg[1] (.RN (rst_n), .CK (clk), .D (n_135),
       .Q (dec_s6[1]), .QN (UNCONNECTED16));
  DFFRX1 \u_memory_dec_s2_reg[3] (.RN (rst_n), .CK (clk), .D (n_131),
       .Q (dec_s2[3]), .QN (UNCONNECTED17));
  DFFRX1 \u_memory_dec_s4_reg[3] (.RN (rst_n), .CK (clk), .D (n_129),
       .Q (dec_s4[3]), .QN (UNCONNECTED18));
  NAND2X1 g6569__5107(.A (n_151), .B (n_149), .Y (n_166));
  OR2X1 g6566__6260(.A (n_151), .B (n_148), .Y (n_163));
  NAND2X1 g6565__4319(.A (n_151), .B (n_148), .Y (n_162));
  OR2X1 g6570__8428(.A (n_151), .B (n_149), .Y (n_165));
  CLKINVX1 g6571(.A (n_147), .Y (n_158));
  MX2X1 g6583__5526(.A (dec_s6[0]), .B (n_143), .S0 (n_145), .Y
       (n_146));
  CLKINVX1 g6582(.A (n_167), .Y (n_144));
  AOI22X1 g6581__6783(.A0 (n_115), .A1 (n_143), .B0 (n_126), .B1
       (n_136), .Y (n_147));
  OAI22X1 g6591__3680(.A0 (n_107), .A1 (n_142), .B0 (n_64), .B1
       (n_141), .Y (n_150));
  OAI22X1 g6590__1617(.A0 (n_75), .A1 (n_142), .B0 (n_73), .B1 (n_141),
       .Y (n_172));
  MX2X1 g6578__2802(.A (n_143), .B (dec_s4[0]), .S0 (n_215), .Y
       (n_140));
  MX2X1 g6574__1705(.A (dec_s2[2]), .B (n_142), .S0 (n_217), .Y
       (n_139));
  MX2X1 g6572__5122(.A (n_142), .B (dec_s4[2]), .S0 (n_215), .Y
       (n_138));
  MX2X1 g6579__8246(.A (dec_s2[0]), .B (n_143), .S0 (n_217), .Y
       (n_137));
  DFFRX1 \u_memory_o_data_reg[7] (.RN (rst_n), .CK (clk), .D (n_127),
       .Q (o_data[7]), .QN (UNCONNECTED19));
  OAI22X1 g6580__7098(.A0 (n_66), .A1 (n_136), .B0 (n_116), .B1
       (n_143), .Y (n_152));
  MX2X1 g6584__6131(.A (dec_s6[1]), .B (n_134), .S0 (n_145), .Y
       (n_135));
  AOI22X1 g6587__1881(.A0 (n_94), .A1 (n_130), .B0 (n_119), .B1
       (n_128), .Y (n_167));
  AOI22X1 g6588__5115(.A0 (n_85), .A1 (n_134), .B0 (n_120), .B1
       (n_125), .Y (n_164));
  MX2X1 g6589__7482(.A (n_261), .B (n_69), .S0 (n_134), .Y (n_148));
  MX2X1 g6575__4733(.A (dec_s2[1]), .B (n_134), .S0 (n_217), .Y
       (n_133));
  MX2X1 g6573__6161(.A (n_134), .B (dec_s4[1]), .S0 (n_215), .Y
       (n_132));
  MX2X1 g6577__9315(.A (dec_s2[3]), .B (n_130), .S0 (n_217), .Y
       (n_131));
  MX2X1 g6576__9945(.A (n_130), .B (dec_s4[3]), .S0 (n_215), .Y
       (n_129));
  OAI22X1 g6592__2883(.A0 (n_71), .A1 (n_128), .B0 (n_95), .B1 (n_130),
       .Y (n_149));
  MX2X1 g6547__2346(.A (n_122), .B (o_data[7]), .S0 (n_123), .Y
       (n_127));
  CLKINVX2 g6594(.A (n_141), .Y (n_142));
  DFFRX1 \u_memory_o_data_reg[6] (.RN (rst_n), .CK (clk), .D (n_124),
       .Q (o_data[6]), .QN (UNCONNECTED20));
  INVX2 g6600(.A (n_136), .Y (n_143));
  DFFRX1 \u_memory_rx_reg_reg[9] (.RN (rst_n), .CK (clk), .D (n_102),
       .Q (\u_memory_rx_reg[9]_306 ), .QN (UNCONNECTED21));
  DFFRX1 \u_memory_rx_reg_reg[5] (.RN (rst_n), .CK (clk), .D (n_105),
       .Q (\u_memory_rx_reg[5]_302 ), .QN (UNCONNECTED22));
  DFFRX1 \u_memory_rx_reg_reg[11] (.RN (rst_n), .CK (clk), .D (n_111),
       .Q (\u_memory_rx_reg[11]_308 ), .QN (UNCONNECTED23));
  DFFRX1 \u_memory_rx_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_99), .Q
       (\u_memory_rx_reg[2]_299 ), .QN (UNCONNECTED24));
  DFFRX1 \u_memory_rx_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_101),
       .Q (\u_memory_rx_reg[0]_297 ), .QN (UNCONNECTED25));
  NAND2X1 g6597__1666(.A (n_74), .B (n_108), .Y (n_141));
  NAND2X1 g6603__7410(.A (n_126), .B (n_117), .Y (n_136));
  DFFRX1 \u_memory_rx_reg_reg[14] (.RN (rst_n), .CK (clk), .D (n_109),
       .Q (rx_reg[14]), .QN (n_2));
  CLKINVX2 g6595(.A (n_128), .Y (n_130));
  CLKINVX2 g6596(.A (n_125), .Y (n_134));
  DFFRX1 \u_memory_rx_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_100),
       .Q (\u_memory_rx_reg[1]_298 ), .QN (UNCONNECTED26));
  DFFRX1 \u_memory_rx_reg_reg[10] (.RN (rst_n), .CK (clk), .D (n_113),
       .Q (\u_memory_rx_reg[10]_307 ), .QN (UNCONNECTED27));
  DFFRX1 \u_memory_rx_reg_reg[6] (.RN (rst_n), .CK (clk), .D (n_112),
       .Q (\u_memory_rx_reg[6]_303 ), .QN (UNCONNECTED28));
  DFFRX1 \u_memory_rx_reg_reg[4] (.RN (rst_n), .CK (clk), .D (n_114),
       .Q (\u_memory_rx_reg[4]_301 ), .QN (UNCONNECTED29));
  DFFRX1 \u_memory_rx_reg_reg[7] (.RN (rst_n), .CK (clk), .D (n_104),
       .Q (\u_memory_rx_reg[7]_304 ), .QN (UNCONNECTED30));
  DFFRX1 \u_memory_rx_reg_reg[8] (.RN (rst_n), .CK (clk), .D (n_103),
       .Q (\u_memory_rx_reg[8]_305 ), .QN (UNCONNECTED31));
  DFFRX1 \u_memory_rx_reg_reg[3] (.RN (rst_n), .CK (clk), .D (n_98), .Q
       (\u_memory_rx_reg[3]_300 ), .QN (UNCONNECTED32));
  DFFRX1 \u_memory_rx_reg_reg[15] (.RN (rst_n), .CK (clk), .D (n_106),
       .Q (rx_reg[15]), .QN (n_6));
  DFFRX1 \u_memory_rx_reg_reg[13] (.RN (rst_n), .CK (clk), .D (n_110),
       .Q (rx_reg[13]), .QN (n_3));
  DFFRX1 \u_memory_rx_reg_reg[12] (.RN (rst_n), .CK (clk), .D (n_118),
       .Q (rx_reg[12]), .QN (n_7));
  MX2X1 g6585__6417(.A (n_121), .B (o_data[6]), .S0 (n_123), .Y
       (n_124));
  MX4X1 g6586__5477(.A (dec_s2[0]), .B (dec_s2[2]), .C (dec_s2[1]), .D
       (dec_s2[3]), .S0 (n_76), .S1 (n_121), .Y (n_122));
  NAND2X1 g6599__2398(.A (n_120), .B (n_87), .Y (n_125));
  NAND2X1 g6598__5107(.A (n_119), .B (n_96), .Y (n_128));
  OAI21X1 g6634__6260(.A0 (n_7), .A1 (n_236), .B0 (n_60), .Y (n_118));
  OAI21X1 g6617__4319(.A0 (n_67), .A1 (n_116), .B0 (n_115), .Y (n_117));
  CLKINVX1 g6625(.A (n_93), .Y (n_114));
  CLKINVX1 g6626(.A (n_90), .Y (n_113));
  CLKINVX1 g6627(.A (n_89), .Y (n_112));
  CLKINVX1 g6628(.A (n_88), .Y (n_111));
  OAI21X1 g6630__8428(.A0 (n_3), .A1 (n_236), .B0 (n_63), .Y (n_110));
  OAI21X1 g6631__5526(.A0 (n_2), .A1 (n_236), .B0 (n_62), .Y (n_109));
  OAI21X1 g6616__6783(.A0 (n_65), .A1 (n_107), .B0 (n_72), .Y (n_108));
  OAI21X1 g6635__3680(.A0 (n_6), .A1 (n_236), .B0 (n_61), .Y (n_106));
  CLKINVX1 g6638(.A (n_97), .Y (n_105));
  CLKINVX1 g6639(.A (n_78), .Y (n_104));
  CLKINVX1 g6640(.A (n_83), .Y (n_103));
  CLKINVX1 g6641(.A (n_82), .Y (n_102));
  INVX1 g6642(.A (n_81), .Y (n_101));
  INVX1 g6643(.A (n_80), .Y (n_100));
  INVX1 g6644(.A (n_79), .Y (n_99));
  INVX1 g6645(.A (n_84), .Y (n_98));
  DFFRX1 \u_memory_o_data_reg[5] (.RN (rst_n), .CK (clk), .D (n_77), .Q
       (o_data[5]), .QN (UNCONNECTED33));
  AOI222X1 g6646__1617(.A0 (\u_memory_rx_reg[1]_298 ), .A1 (n_234), .B0
       (i_data[5]), .B1 (n_92), .C0 (\u_memory_rx_reg[5]_302 ), .C1
       (n_91), .Y (n_97));
  OAI21X1 g6615__2802(.A0 (n_70), .A1 (n_95), .B0 (n_94), .Y (n_96));
  AOI222X1 g6629__1705(.A0 (\u_memory_rx_reg[0]_297 ), .A1 (n_234), .B0
       (i_data[4]), .B1 (n_92), .C0 (\u_memory_rx_reg[4]_301 ), .C1
       (n_91), .Y (n_93));
  AOI222X1 g6632__5122(.A0 (\u_memory_rx_reg[6]_303 ), .A1 (n_234), .B0
       (i_data[10]), .B1 (n_92), .C0 (\u_memory_rx_reg[10]_307 ), .C1
       (n_91), .Y (n_90));
  AOI222X1 g6633__8246(.A0 (\u_memory_rx_reg[2]_299 ), .A1 (n_234), .B0
       (i_data[6]), .B1 (n_92), .C0 (\u_memory_rx_reg[6]_303 ), .C1
       (n_91), .Y (n_89));
  AOI222X1 g6636__7098(.A0 (\u_memory_rx_reg[7]_304 ), .A1 (n_234), .B0
       (i_data[11]), .B1 (n_92), .C0 (\u_memory_rx_reg[11]_308 ), .C1
       (n_91), .Y (n_88));
  OAI21X1 g6614__6131(.A0 (n_68), .A1 (n_261), .B0 (n_85), .Y (n_87));
  AOI22X1 g6653__1881(.A0 (\u_memory_rx_reg[3]_300 ), .A1 (n_91), .B0
       (i_data[3]), .B1 (n_92), .Y (n_84));
  AOI222X1 g6648__5115(.A0 (\u_memory_rx_reg[4]_301 ), .A1 (n_234), .B0
       (i_data[8]), .B1 (n_92), .C0 (\u_memory_rx_reg[8]_305 ), .C1
       (n_91), .Y (n_83));
  AOI222X1 g6649__7482(.A0 (\u_memory_rx_reg[5]_302 ), .A1 (n_234), .B0
       (i_data[9]), .B1 (n_92), .C0 (\u_memory_rx_reg[9]_306 ), .C1
       (n_91), .Y (n_82));
  AOI22X1 g6650__4733(.A0 (\u_memory_rx_reg[0]_297 ), .A1 (n_91), .B0
       (i_data[0]), .B1 (n_92), .Y (n_81));
  AOI22X1 g6651__6161(.A0 (\u_memory_rx_reg[1]_298 ), .A1 (n_91), .B0
       (i_data[1]), .B1 (n_92), .Y (n_80));
  AOI22X1 g6652__9315(.A0 (\u_memory_rx_reg[2]_299 ), .A1 (n_91), .B0
       (i_data[2]), .B1 (n_92), .Y (n_79));
  AOI222X1 g6647__9945(.A0 (\u_memory_rx_reg[3]_300 ), .A1 (n_234), .B0
       (i_data[7]), .B1 (n_92), .C0 (\u_memory_rx_reg[7]_304 ), .C1
       (n_91), .Y (n_78));
  MX2X1 g6601__2883(.A (n_76), .B (o_data[5]), .S0 (n_123), .Y (n_77));
  MX4X1 g6602__2346(.A (dec_s3[0]), .B (dec_s3[2]), .C (dec_s3[1]), .D
       (dec_s3[3]), .S0 (n_45), .S1 (n_76), .Y (n_121));
  CLKINVX1 g6656(.A (n_74), .Y (n_75));
  CLKINVX1 g6657(.A (n_72), .Y (n_73));
  DFFRX1 \u_memory_o_data_reg[4] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (o_data[4]), .QN (UNCONNECTED34));
  DFFRX1 \u_control_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (state[0]), .QN (UNCONNECTED35));
  CLKINVX1 g6671(.A (n_70), .Y (n_71));
  CLKINVX1 g6670(.A (n_68), .Y (n_69));
  CLKINVX1 g6658(.A (n_66), .Y (n_67));
  CLKINVX1 g6672(.A (n_64), .Y (n_65));
  INVX2 g6685(.A (n_91), .Y (n_236));
  AOI22X1 g6676__1666(.A0 (\u_memory_rx_reg[9]_306 ), .A1 (n_234), .B0
       (i_data[13]), .B1 (n_92), .Y (n_63));
  AOI22X1 g6674__7410(.A0 (\u_memory_rx_reg[10]_307 ), .A1 (n_234), .B0
       (i_data[14]), .B1 (n_92), .Y (n_62));
  AOI22X1 g6673__6417(.A0 (\u_memory_rx_reg[11]_308 ), .A1 (n_234), .B0
       (i_data[15]), .B1 (n_92), .Y (n_61));
  AOI22X1 g6677__5477(.A0 (\u_memory_rx_reg[8]_305 ), .A1 (n_234), .B0
       (i_data[12]), .B1 (n_92), .Y (n_60));
  NAND2X1 g6667__2398(.A (n_59), .B (n_56), .Y (n_126));
  DFFRX1 \u_memory_o_data_reg[3] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (o_data[3]), .QN (UNCONNECTED36));
  AOI211X1 g6669__5107(.A0 (pm01[1]), .A1 (n_52), .B0 (n_47), .C0
       (n_29), .Y (n_66));
  NAND2X1 g6668__6260(.A (n_59), .B (n_58), .Y (n_72));
  DFFRX1 \u_control_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_39), .Q
       (state[2]), .QN (n_11));
  NAND2X1 g6661__4319(.A (n_57), .B (n_58), .Y (n_115));
  NAND2X1 g6662__8428(.A (n_57), .B (n_56), .Y (n_74));
  NAND2X1 g6686__5526(.A (pm11[0]), .B (n_238), .Y (n_55));
  NAND2X1 g6687__6783(.A (pm10[0]), .B (n_238), .Y (n_54));
  NAND2X1 g6688__3680(.A (pm01[0]), .B (n_238), .Y (n_53));
  AOI211X1 g6681__1617(.A0 (pm00[1]), .A1 (n_52), .B0 (n_32), .C0
       (n_37), .Y (n_107));
  OAI211X1 g6678__1705(.A0 (n_51), .A1 (n_42), .B0 (n_49), .C0 (n_48),
       .Y (n_68));
  AND2X1 g6684__5122(.A (n_38), .B (n_33), .Y (n_116));
  AOI221X1 g6683__8246(.A0 (pm10[0]), .A1 (n_36), .B0 (pm10[1]), .B1
       (n_8), .C0 (n_50), .Y (n_95));
  OAI211X1 g6679__7098(.A0 (n_51), .A1 (n_44), .B0 (n_49), .C0 (n_48),
       .Y (n_70));
  NOR2X1 g6680__6131(.A (n_47), .B (n_35), .Y (n_64));
  AND2X2 g6692__1881(.A (n_233), .B (n_238), .Y (n_91));
  MX2X1 g6654__5115(.A (n_45), .B (o_data[4]), .S0 (n_123), .Y (n_46));
  NAND2X1 g6659__7482(.A (n_44), .B (n_40), .Y (n_94));
  DFFRX1 \u_memory_o_data_reg[2] (.RN (rst_n), .CK (clk), .D (n_25), .Q
       (o_data[2]), .QN (UNCONNECTED37));
  MX4X1 g6655__4733(.A (dec_s4[2]), .B (dec_s4[0]), .C (dec_s4[3]), .D
       (dec_s4[1]), .S0 (n_30), .S1 (n_45), .Y (n_76));
  OR3X1 g6675__6161(.A (n_145), .B (n_92), .C (n_217), .Y (n_43));
  NAND2X1 g6665__9315(.A (n_44), .B (n_41), .Y (n_120));
  NAND2X1 g6663__9945(.A (n_42), .B (n_41), .Y (n_119));
  NAND2X1 g6666__2883(.A (n_42), .B (n_40), .Y (n_85));
  NAND2X1 g6712__2346(.A (n_21), .B (n_215), .Y (n_39));
  CLKINVX1 g6701(.A (n_37), .Y (n_38));
  AOI21X1 g6697__1666(.A0 (pm00[0]), .A1 (n_36), .B0 (pm00[1]), .Y
       (n_56));
  CLKINVX2 g6703(.A (n_234), .Y (n_238));
  OAI21X1 g6693__7410(.A0 (n_34), .A1 (n_59), .B0 (n_28), .Y (n_35));
  AOI21X1 g6696__6417(.A0 (pm00[1]), .A1 (n_5), .B0 (n_32), .Y (n_33));
  OAI21X1 g6695__5477(.A0 (n_30), .A1 (n_123), .B0 (n_22), .Y (n_31));
  AOI21X1 g6689__2398(.A0 (pm01[0]), .A1 (n_36), .B0 (pm01[1]), .Y
       (n_58));
  DFFRX1 \u_control_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_20), .Q
       (state[1]), .QN (UNCONNECTED38));
  CLKINVX1 g6702(.A (n_28), .Y (n_29));
  AOI21X1 g6698__6260(.A0 (pm10[0]), .A1 (n_26), .B0 (pm10[1]), .Y
       (n_41));
  NAND2X1 g6706__4319(.A (pm11[0]), .B (n_36), .Y (n_49));
  AOI21X1 g6699__8428(.A0 (pm11[0]), .A1 (n_26), .B0 (pm11[1]), .Y
       (n_40));
  MX2X1 g6694__5526(.A (dec_s7), .B (o_data[2]), .S0 (n_123), .Y
       (n_25));
  DFFRX1 u_memory_o_done_reg(.RN (rst_n), .CK (clk), .D (n_17), .Q
       (o_done), .QN (UNCONNECTED39));
  NOR2X1 g6707__6783(.A (n_24), .B (n_36), .Y (n_37));
  AOI21X1 g6718__3680(.A0 (pm10[0]), .A1 (n_23), .B0 (n_36), .Y (n_50));
  OR2X2 g6710__1617(.A (n_16), .B (n_145), .Y (n_234));
  NAND2X1 g6714__2802(.A (o_data[3]), .B (n_123), .Y (n_22));
  OAI21X1 g6715__1705(.A0 (pm11[1]), .A1 (n_1), .B0 (n_26), .Y (n_48));
  MX4X1 g6700__5122(.A (dec_s5[1]), .B (dec_s5[3]), .C (dec_s5[0]), .D
       (dec_s5[2]), .S0 (dec_s7), .S1 (n_30), .Y (n_45));
  NOR2X1 g6709__8246(.A (state[0]), .B (n_19), .Y (n_217));
  CLKINVX1 g6721(.A (n_145), .Y (n_21));
  AOI21X1 g6713__7098(.A0 (state[0]), .A1 (state[1]), .B0 (n_19), .Y
       (n_20));
  NAND2X1 g6708__6131(.A (pm01[0]), .B (n_26), .Y (n_28));
  AOI21X1 g6716__1881(.A0 (pm01[0]), .A1 (n_34), .B0 (n_26), .Y (n_47));
  AOI21X1 g6717__5115(.A0 (pm00[0]), .A1 (n_18), .B0 (n_26), .Y (n_32));
  INVX2 g6726(.A (n_151), .Y (n_153));
  NOR2X1 g6724__7482(.A (state[0]), .B (n_15), .Y (n_145));
  CLKINVX1 g6722(.A (n_123), .Y (n_17));
  CLKINVX2 g6711(.A (n_92), .Y (n_233));
  INVX2 g6727(.A (n_26), .Y (n_36));
  NAND2X1 g6725__4733(.A (state[0]), .B (n_14), .Y (n_123));
  AND3X2 g6719__6161(.A (en), .B (n_11), .C (n_12), .Y (n_92));
  CLKINVX1 g6720(.A (n_16), .Y (n_19));
  CLKAND2X2 g6730__9315(.A (n_44), .B (n_42), .Y (n_26));
  NAND2X1 g6729__9945(.A (n_173), .B (n_174), .Y (n_151));
  CLKINVX1 g6732(.A (n_14), .Y (n_15));
  CLKINVX1 g6733(.A (n_173), .Y (n_13));
  NOR2X1 g6723__2883(.A (state[2]), .B (n_12), .Y (n_16));
  NAND3X1 g6731__2346(.A (state[0]), .B (n_11), .C (state[1]), .Y
       (n_215));
  CLKINVX1 g6736(.A (n_174), .Y (n_10));
  CLKINVX1 g6735(.A (n_44), .Y (n_9));
  CLKINVX1 g6734(.A (n_42), .Y (n_8));
  AOI22X1 g6728__1666(.A0 (dec_s6[0]), .A1 (n_0), .B0 (dec_s6[1]), .B1
       (dec_s7), .Y (n_30));
  NOR2X1 g6737__7410(.A (n_11), .B (state[1]), .Y (n_14));
  CLKINVX1 g6742(.A (n_52), .Y (n_57));
  NAND2X1 g6738__6417(.A (rx_reg[13]), .B (n_7), .Y (n_173));
  NAND2X1 g6740__5477(.A (rx_reg[14]), .B (n_6), .Y (n_44));
  INVX2 g6744(.A (n_59), .Y (n_5));
  CLKINVX1 g6743(.A (n_176), .Y (n_4));
  NAND2X1 g6741__2398(.A (rx_reg[12]), .B (n_3), .Y (n_174));
  NAND2X1 g6739__5107(.A (rx_reg[15]), .B (n_2), .Y (n_42));
  NAND2X1 g6748__6260(.A (rx_reg[14]), .B (rx_reg[15]), .Y (n_59));
  NOR2X1 g6749__4319(.A (rx_reg[12]), .B (rx_reg[13]), .Y (n_177));
  NOR2X1 g6745__8428(.A (state[0]), .B (state[1]), .Y (n_12));
  NOR2X1 g6746__5526(.A (rx_reg[14]), .B (rx_reg[15]), .Y (n_52));
  NAND2X1 g6747__6783(.A (rx_reg[12]), .B (rx_reg[13]), .Y (n_176));
  AOI221X1 g2(.A0 (pm10[1]), .A1 (n_9), .B0 (n_36), .B1 (pm10[0]), .C0
       (n_50), .Y (n_261));
endmodule

